name: condofy
description: "Um app para síndicos monitorarem seus condomínios."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  mobx: ^2.3.0
  flutter_mobx: ^2.2.0

  get_it: ^7.6.7

  shared_preferences: ^2.2.2

  go_router: ^13.2.0

  webview_flutter:

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.8
  mobx_codegen: ^2.6.0

  flutter_lints: ^3.0.0

  mockito: ^5.4.4


flutter:
  uses-material-design: true

